name: cupertino_fullscreen_modal
description: Cupertino like fullscreen modal.
version: 0.0.1
author: Luke Urban
homepage: https://github.com/lukeurban/cupertino_fullscreen_modal

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
